@url = http://localhost:3000
@authUser = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb3JyZW8iOiJ0M0B0LmNvbSIsInVpZCI6MywiaWF0IjoxNTc1MTc5NTM1LCJleHAiOjE1NzUxODMxMzV9.eavDo40JlQIe5zk5wQdmkO5Ybvt6wL_wXbtgOpSYD40

### LOGIN
POST {{url}}/api/login
Content-Type: application/json

{
  "email":"admin@correo.com",
  "password":"admin"
}

### JAVI LOGIN
POST {{url}}/api/login
Content-Type: application/json

{
  "email":"diego@correo.com",
  "password":"diego"
}

### GUARDAR USUARIO EN LA BASE DE DATOS (SING UP)
POST  {{url}}/api/users
Content-Type: application/json

{
    "firstName":"Admin",
    "lastName":"User",
    "email":"admin@correo.com",
    "admin":"1",
    "password":"admin"
}

### OBTENER TODOS LOS USUARIOS
GET  {{url}}/api/users
Content-Type: application/json
x-auth-user: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGNvcnJlby5jb20iLCJpZCI6MywiaWF0IjoxNTc1NDg5MzY4LCJleHAiOjE1NzU1MTA5Njh9.FBt6Dys03GPwYrDx0q--mAE7nyGay2qWL6x9zExZpIE

### OBTENER USUARIO POR ID
GET  {{url}}/api/users/4
Content-Type: application/json
x-auth-user: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGNvcnJlby5jb20iLCJpZCI6MywiaWF0IjoxNTc1NDg5MzY4LCJleHAiOjE1NzU1MTA5Njh9.FBt6Dys03GPwYrDx0q--mAE7nyGay2qWL6x9zExZpIE

### MODIFICAR USUARIO
PUT  {{url}}/api/users/3
Content-Type: application/json
x-auth-user: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRpZWdvQGNvcnJlby5jb20iLCJpZCI6MywiaWF0IjoxNTc1NDkwNDU5LCJleHAiOjE1NzU1MTIwNTl9.eLx7apgMcreV81Lz1BM-32cW5VDc0I-ff1P32M8W2Q8

{
    "firstName":"Diego",
    "lastName":"Ascencio Cano",
    "email":"diego@correo.com",
    "admin":"0",
    "password":"diego"
}

### DELETE USER
DELETE  {{url}}/api/users/3
Content-Type: application/json
x-auth-user: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImphdmllckBjb3JyZW8uY29tIiwiaWQiOjMsImlhdCI6MTU3NTQxMTMyNSwiZXhwIjoxNTc1NDMyOTI1fQ.r4PjLoJQ3621Dmstvq2TE7xd3F0XmPUaUWM1BS8LakI


### GUARDAR QUIZZ EN LA BASE DE DATOS
POST  {{url}}/api/quizz
Content-Type: application/json
x-auth-user: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGNvcnJlby5jb20iLCJpZCI6MywiaWF0IjoxNTc1NDg5NjAyLCJleHAiOjE1NzU1MTEyMDJ9.nhb6JRYrEbvDyBdStV4h6loWdNOUSrnPQ5RuoicCIjw

{
      "name": "Examen 2",
      "description": "Descripcion",
      "url": "",
      "creator": "4",
      "questions": [
        {
          "question": "¿Cuál es tu nieve fav?",
          "time": 90,
          "answers": [
            {
              "answer": "Vainilla",
              "correct": true
            },
            {
              "answer": "Chocolate",
              "correct": false
            }
          ]
        },
        {
          "question": "¿Qué paleta te gusta más",
          "time": 60,
          "answers": [
            {
              "answer": "Limón",
              "correct": true
            },
            {
              "answer": "Vainilla",
              "correct": false
            }
          ]
        }
      ]
    }


### GUARDAR QUIZZ EN LA BASE DE DATOS
POST  {{url}}/api/quizz
Content-Type: application/json
x-auth-user: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImphdmllckBjb3JyZW8uY29tIiwiaWQiOjMsImlhdCI6MTU3NTQxMTMyNSwiZXhwIjoxNTc1NDMyOTI1fQ.r4PjLoJQ3621Dmstvq2TE7xd3F0XmPUaUWM1BS8LakI

 {
      "name": "Quizz 2",
      "description": "Esta es la segunda prueba",
      "url": "",
      "creator": "4",
      "questions": [
        {
          "question": "YA JALAAAAA",
          "time": "30",
          "url": "",
          "answers": [
            {
              "answer": "dfgfdlskñjg",
              "correct": false
            },
            {
              "answer": "sdgfsdg",
              "correct": false
            },
            {
              "answer": "asfsdf",
              "correct": false
            }
          ]
        }
      ]
    }

### OBTENER TODOS LOS QUIZZES DE UN USUARIO
GET  {{url}}/api/quizz
x-auth-user: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGNvcnJlby5jb20iLCJpZCI6NCwiaWF0IjoxNTc1NDIwODY0LCJleHAiOjE1NzU0NDI0NjR9.wD1ryJTlfwaT35_TYIKpA2VEEMAkSKGTXoUOsAKQ7rY


### OBTENER QUIZZ ID
GET  {{url}}/api/quizz/1001
x-auth-user: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGNvcnJlby5jb20iLCJpZCI6NiwiaWF0IjoxNTc1NDk1ODQzLCJleHAiOjE1NzU1MTc0NDN9.rPvsd_oHhfL3b12lE-47Mko7r-YLDiRmdxCao8no4ZU


### MODIFICAR QUIZZ
PUT  {{url}}/api/quizz/1009
Content-Type: application/json
x-auth-user: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGNvcnJlby5jb20iLCJpZCI6NiwiaWF0IjoxNTc1NDk1ODQzLCJleHAiOjE1NzU1MTc0NDN9.rPvsd_oHhfL3b12lE-47Mko7r-YLDiRmdxCao8no4ZU

{
      "name": "Test modificado",
      "description": "Modificado",
      "url": "asdfasdfasdf",
      "creator": "4",
      "bestScore": 100,
      "worstScore": 30,
      "played": 60,
      "questions": [
        {
          "question": "¿Cuál es tu nieve fav?",
          "time": 90,
          "answers": [
            {
              "answer": "Vainilla",
              "correct": true
            },
            {
              "answer": "Chocolate",
              "correct": false
            }
          ]
        },
        {
          "question": "¿Qué paleta te gusta más",
          "time": 60,
          "answers": [
            {
              "answer": "Limón",
              "correct": true
            },
            {
              "answer": "Vainilla",
              "correct": false
            }
          ]
        }
      ],
      "correct": [
        [
          "Vainilla",
          null
        ],
        [
          "Limón",
          null
        ],[
          "Exito",
          null
        ]
      ]
    }


### DELETE QUIZZ
DELETE  {{url}}/api/quizz/1005
Content-Type: application/json
x-auth-user: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGNvcnJlby5jb20iLCJpZCI6NCwiaWF0IjoxNTc1NDIwODY0LCJleHAiOjE1NzU0NDI0NjR9.wD1ryJTlfwaT35_TYIKpA2VEEMAkSKGTXoUOsAKQ7rY

### GUARDAR ReSULTADO EN LA BASE DE DATOS
POST  {{url}}/api/quizzresults
Content-Type: application/json
x-auth-user: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGNvcnJlby5jb20iLCJpZCI6NiwiaWF0IjoxNTc1NDk1ODQzLCJleHAiOjE1NzU1MTc0NDN9.rPvsd_oHhfL3b12lE-47Mko7r-YLDiRmdxCao8no4ZU

{
      "quizz": 1001,
      "user": 6,
      "nickname": "TEST API DOC"
}

### OBTENER TODOS LOS QUIZZES
GET  {{url}}/api/quizzresults
x-auth-user: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGNvcnJlby5jb20iLCJpZCI6NiwiaWF0IjoxNTc1NDk1ODQzLCJleHAiOjE1NzU1MTc0NDN9.rPvsd_oHhfL3b12lE-47Mko7r-YLDiRmdxCao8no4ZU


### OBTENER QUIZZRESULT POR ID
GET  {{url}}/api/quizzresults/19
x-auth-user: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGNvcnJlby5jb20iLCJpZCI6NiwiaWF0IjoxNTc1NDk2NDIwLCJleHAiOjE1NzU1MTgwMjB9.SGMSkm__MkH9CmKXSCstt2tRM9vEJFyMvbiFZxowzrE


### MODIFICAR QUIZZRESULT
PUT  {{url}}/api/quizzresults/25
Content-Type: application/json
x-auth-user: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGNvcnJlby5jb20iLCJpZCI6NiwiaWF0IjoxNTc1NDk1ODQzLCJleHAiOjE1NzU1MTc0NDN9.rPvsd_oHhfL3b12lE-47Mko7r-YLDiRmdxCao8no4ZU

{
      "quizz": 1001,
      "user": 6,
      "nickname": "Javi",
      "score": 50,
      "time": 77,
      "answers": [
        {
          "question": "question number 1",
          "correct": true,
          "time": 55,
          "answer": "A"
        },
        {
          "question": "question number 2",
          "correct": false,
          "time": 22,
          "answer": "B"
        }
      ]
    }

###
POST  {{url}}/api/login
Content-Type: application/json

{
    "correo":"t2@t.com",
    "password":"12345"
}

### ?nombre=L

GET  {{url}}/api/users?page=0
x-user-token: {{authUser}}

###
GET  {{url}}/api/users/t@t.com
Content-Type: application/json
x-user-token: {{authUser}}
###
PUT  {{url}}/api/users/t2@t.com
Content-Type: application/json
x-user-token: {{authUser}}

{
    "nombre":"L22",
    "apellido":"G22",
    "password":"12345",
    "correo":"t2@t.com",
    "sexo":"H2",
    "fecha":"10-10-2012"
}

###
DELETE  {{url}}/api/users/test2@test.com
Content-Type: application/json
x-user-token: {{authUser}}

###
GET {{url}}/api/users/t@t.com
Content-Type: application/json
x-user-token: {{authUser}}